all: 
	{ cat day1.txt | python3 mapper.py | sort | python3 combiner.py \
	&& cat day2.txt | python3 mapper.py | sort | python3 combiner.py \
	&& cat day3.txt | python3 mapper.py | sort | python3 combiner.py \
	&& cat day4.txt | python3 mapper.py | sort | python3 combiner.py \
	&& cat day5.txt | python3 mapper.py | sort | python3 combiner.py \
	&& cat day6.txt | python3 mapper.py | sort | python3 combiner.py \
	&& cat day7.txt | python3 mapper.py | sort | python3 combiner.py \
	&& cat day8.txt | python3 mapper.py | sort | python3 combiner.py \
	&& cat day9.txt | python3 mapper.py | sort | python3 combiner.py \
	&& cat day10.txt | python3 mapper.py | sort | python3 combiner.py ; } | sort |  python3 reducer.py > network.txt
